name: my_pt_app
description: A fitness app for personal trainers and clients

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  cloud_functions: ^3.0.4
  form_field_validator: ^1.1.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  firebase_storage: ^8.0.0
  image_picker: ^0.7.3
  image_cropper: ^1.4.0
  path_provider: ^2.0.1
  http:
  shared_preferences: ^2.0.5
  file_picker: ^3.0.0
  emoji_picker: ^0.0.2
  video_player: ^2.1.1
  video_thumbnail: ^0.4.3
  image_gallery_saver: ^1.7.0
  permission_handler: ^8.0.1
  dio: ^4.0.0
  flutter_keyboard_visibility: ^5.0.2
  scrollable_positioned_list: ^0.2.3
  tuple: ^2.0.0
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.1.0+1
  url_launcher: ^6.0.15
  syncfusion_flutter_datepicker: ^19.3.57
  flutter_slidable: ^1.1.0
  charts_flutter: ^0.12.0
  line_icons: ^2.0.1
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  device_info_plus: ^3.2.1
  google_fonts: ^2.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/gifs/loading.gif
    - assets/icons/



