"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.weightRecords = exports.posingTutorials = exports.exerciseTutorials = exports.trackers = exports.recentActivity = exports.coachTokens = exports.clientTokens = exports.clientPerformance = exports.dayExercisePlans = exports.dayMealPlans = exports.clientManagement = exports.exercises = exports.exercisePlans = exports.meals = exports.mealPlans = exports.coachChats = exports.chatContentItems = exports.myClients = exports.myCoach = exports.coaches = exports.clients = exports.users = void 0;
exports.users = "users";
exports.clients = "clients";
exports.coaches = "coaches";
exports.myCoach = "myCoach";
exports.myClients = "myClients";
exports.chatContentItems = "chatContentItems";
exports.coachChats = "coachChats";
exports.mealPlans = "mealPlans";
exports.meals = "meals";
exports.exercisePlans = "exercisePlans";
exports.exercises = "exercises";
exports.clientManagement = "clientManagement";
exports.dayMealPlans = "dayMealPlans";
exports.dayExercisePlans = "dayExercisePlans";
exports.clientPerformance = "clientPerformance";
exports.clientTokens = "clientTokens";
exports.coachTokens = "coachTokens";
exports.recentActivity = "recentActivity";
exports.trackers = "trackers";
exports.exerciseTutorials = "exerciseTutorials";
exports.posingTutorials = "posingTutorials";
exports.weightRecords = "weightRecords";
//# sourceMappingURL=collectionNames.js.map